package mods.roborave.common.modapi;

import mods.common.util.config.ConfigManager;
import mods.common.util.config.Configuration;
import mods.roborave.common.modapi.lib.Strings;
import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = ModAPI.MODID, version = ModAPI.VERSION,name=ModAPI.NAME,guiFactory="mods.roborave.client.gui.GuiFactoryHandler")
public class ModAPI extends DummyModContainer
{
    public static final String MODID = "Mod-API-Nightly";
    public static final String VERSION = Strings.Version+ Strings.getBuild;
    public static final String NAME = "ModAPI-Nly";
    
    @Mod.Instance(ModAPI.MODID)
    private static ModAPI instance;
    
    @Mod.Metadata(ModAPI.MODID)
	private static ModMetadata meta;
    
	private boolean dev;
    
    @Mod.EventHandler()
    public void Preinit(FMLPreInitializationEvent event)
    {
    	meta= event.getModMetadata();
    	meta.autogenerated=false;
    	meta.name=instance.getName();
    	meta.modId=instance.getModId();
    	meta.version=instance.getVersion();
    	meta.description="this was built at"+Strings.getTimeStamp+"\n"+
    	"This my version of a Mod-API"+
    	" It will be built nightly";
    	
    	ConfigManager.CreateConfig(event, MODID, NAME);
    	ConfigManager.config.load();
    	this.setDev(ConfigManager.getBoolean("Developer Mode", Configuration.CATEGORY_GENERAL, false, "This enables Developer for Mod-API. WIP"));
    	ConfigManager.config.save();
    }
    
    
    @EventHandler
    public void init(FMLInitializationEvent event)
    {

    }
   
	@Override
	public String getModId() 
	{
		return MODID;
	}
	
	@Override
	public String getName() 
	{
		return NAME;
	}
	
	@Override
	public String getVersion() 
	{
		return Strings.Version;
	}


	public boolean isDev() 
	{
		if(dev==true)
		{
			return true;
		}
			else
		{
			return false;
		}
		
	}


	public void setDev(boolean dev) 
	{
		this.dev = dev;
	}
}
